/*
 * This source file was generated by the Gradle 'init' task
 */
package latremedialquiz;
import latremedialquiz.view.Main;

public class App {

    public static void main(String[] args) {
        Main.start();
    }
}
